import Header from '@/components/ui/layout/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/ui/layout/Footer'
import EndFooter from '@/components/ui/layout/EndFooter'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        
        <div className='mx-8 lg:md:px-16 '> <Header /></div>
        <main className='mx-8 lg:md:px-16 '>
          {children}
        </main>
        
          <Footer />
          <EndFooter/>
        
      </body>
    </html>
  )
}
